### ISSUE TITLE
Feature Request: Remove Title bar in windows mode

### ISSUE THREAD

**Issue by xCONFLiCTiONx** [Phrynohyas/eve-o-preview#133]
Removing the title bar in windowed mode would give a bit more space to play with and make it look a lot better too.

**Comment by Phrynohyas** [comment]
Hello

Sorry for the belated answer.

Unfortunately I cannot do this because
a) API used by EVE-O Preview returns window contents with its borders and caption. Removing them will have its performance cost.
b) Formally window caption is a part of UI displayed by the EVE client, so removing it would be a first step towards 'displaying only part of the EVE client UI'
