### ISSUE TITLE
Can't see the thumbnail. It goes fully transparent

### ISSUE THREAD

**Issue by xCONFLiCTiONx** [Phrynohyas/eve-o-preview#136]
Can't see the thumbnail. It goes fully transparent. It works correctly at first until I hover over the thumbnail and just goes blank. That's completely broken for me.

NVidia 9800Gt graphics card

No idea what else to provide here so please ask me.

![image](https://user-images.githubusercontent.com/12835195/49746953-f3634380-fc67-11e8-955c-0c7137bb2897.png)

**Comment by xCONFLiCTiONx** [comment]
Whatever it was seems to have worked itself out. It isn't happening anymore.

**Comment by Phrynohyas** [comment]
Hmm, I thought I've fixed this bug a long ago. It was caused by thumbnail windows disappearing under certain circumstances while their overlay part (one with the char name) remained visible.

Closing for now. Please poke me if the bug comes back (or update to the latest version if you are still on the 3.x versions)
