### ISSUE TITLE
[Bug] Thumbnails Black

### ISSUE THREAD

**Issue by Archetype90** [Phrynohyas/eve-o-preview#165]
The thumbnails work fine at the login screen, but after logging in they are black boxes. Can't seem to get anything to show up. Running the latest version of EVE-O, Windows 10.

**Comment by Archetype90** [comment]
I just noticed as well that if I minimize EVE entirely, I get a static image (not live preview) - but at least it is not black. This does not work unless EVE is completely minimized (IE: Windows + D keys).

I am trying to verify that Aero is enabled (as I am reading you respond that is an issue) and I do see the live preview when I do Windows + Tab for all windows.

**Comment by Phrynohyas** [comment]
https://forums.eveonline.com/t/eve-o-preview-v5-0-1-fua-was-wrong-multi-client-preview-switcher-2020-06-01/4202/492

Logged an investigation issue for HDR support

---

Geeze, finally figured it out.

It was the HDR setting from the DP cable. I must have enabled it when setting up the new PC. As soon as I disabled it, everything worked fine. Side note, using an HDMI cable instead of the DP cable fixes this, as it automatically disables HDR.

Thanks for your help, that was a beast to figure out.
